### ISSUE TITLE
[Proposal] New macOS icon

### ISSUE THREAD

**Issue by davdroman** [aspectron/kdx#21]
Big Sur updated its system icons to resemble iOS (rounded corners aka "squircles").

The current KDX icon looks pretty out of place in the macOS dock:

### Original

<img width="1068" alt="Screenshot 2022-09-10 at 16 26 00" src="https://user-images.githubusercontent.com/2538074/189490213-cc194ab8-2337-42b0-9cee-3768403e3644.png">

Here are a couple ideas for potential new icons that match the look of the OS:

### Variant A

<img width="1064" alt="Screenshot 2022-09-10 at 16 32 23" src="https://user-images.githubusercontent.com/2538074/189490504-10e80854-0b90-4967-9a46-cab8e2b94500.png">

### Variant B

<img width="1067" alt="Screenshot 2022-09-10 at 16 36 26" src="https://user-images.githubusercontent.com/2538074/189490711-50f356dd-1d59-48b2-9f92-852428082edb.png">

Happy to discuss these and potentially put forward a PR with an updated PSD/PNG/ICNS.

**Comment by aspect** [comment]
Thanks for bringing this up. This will be done in the coming weeks. We have a pending rebranding task (new logo etc.) to which I was unable to get to due to travel. I will address this when the rebranding is done.

**Comment by davdroman** [comment]
@aspect great to hear. Happy to offer my assistance if needed but otherwise looking forward to seeing the new look 😄

**Comment by surinder83singh** [comment]
icons updated in 2.12.0
