### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by dawidmosk** [aspectron/kdx#24]
Is anyway to get Linux version? or build normally?

**Comment by trymeouteh** [comment]
Would like an AppImage personally.

https://github.com/aspectron/kdx/issues/25

**Comment by dawidmosk** [comment]
Thank You

**Comment by kryptomicus** [comment]
Where would one get the AppImage? I don't see any releases here... the download is offered on https://kdx.app/ when you arrive:

![image](https://user-images.githubusercontent.com/116469662/203897999-4b7933c3-4adc-4023-8528-ff76ddb91971.png)

but:

![image](https://user-images.githubusercontent.com/116469662/203898021-2f8af763-e4da-4ec0-9752-e1767eeae4e9.png)

**Comment by ATButteaux** [comment]
all linux versions are 404.

**Comment by BarbzYHOOL** [comment]
yes
