### ISSUE TITLE
Cannot Install Wallet On Recent Mac OS X Versions.

### ISSUE THREAD

**Issue by techric** [aspectron/kdx#29]
After downloading wallet software from the KDX website, it cannot be installed on MacOS X.

The error message is "kdx.app cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware." 

Apparently, KDX developers must go through Apple's official verification process. Apple introduced a developer ID system and app review process to reduce the risk of viruses infecting macOS. Before any app can get on the App Store, both the program and the creator are reviewed and approved by Apple. 

So, if one tries to install an app from an unverified developer, or an app from a registered developer, but one that hasn’t been reviewed, they’ll see a corresponding error message.

**Comment by aspect** [comment]
After attempting to run KDX and getting "application is unsigned" error, go to Settings / Privacy & Security and you will see "Open KDX anyway" (or something along these lines).  Once opened, OSX won't ask you again.

OSX used to have "allow application from anywhere" setting, however, they have removed it, and the way it works now is that immediately after running an unsigned application, it offers you to open it anyways from within Privacy & Security panel.

**Comment by supertypo** [comment]
Install works fine using the above mentioned method.
