### ISSUE TITLE
Feature request: balance over time

### ISSUE THREAD

**Issue by thatvalis** [aspectron/kdx#31]
Hi,

It would be very useful to have a "balance over time" feature in KDX.
Not only for keeping track of your balance growth, but also for tax purposes.
If we could also export transactions, with times of entry and balance over time to CSV or Excel that would extremely useful.
Is this possible to implement?
See screenshot from Radiant wallet for inspiration, you can see balance after every transaction.
This makes tax calculations so much easier.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/20734180/205638708-3f01cabf-dbc6-4449-bcd9-ab0e4495880c.png">

**Comment by supertypo** [comment]
Kdx is in maintenance mode. There is a replacement in the works where new features can be implemented. Stay tuned.
