### ISSUE TITLE
miner feature

### ISSUE THREAD

**Issue by demisrael** [aspectron/kdx#4]
I can create 4 miners and each one will be use CPU at full and that is the behavior I expect when I am not using my computer. 
In case I want to use my computer, I want to be able to temporary disable number of miners by simply checking checkbox on KDX and not editing the "Service Configuration" by hand and restarting everything. 
Can such feature can be added? 
Thanks
![image](https://user-images.githubusercontent.com/81626907/112986331-07e5e580-916a-11eb-957a-606daa2dd358.png)

**Comment by demisrael** [comment]
Slide switch is good for that
![image](https://user-images.githubusercontent.com/81626907/112986634-69a64f80-916a-11eb-9dcd-f29e3a7d06d3.png)

**Comment by demisrael** [comment]
I have 4 core CPU, only one miner takes 25% load (1 core). Two miners - 50%, 3 - 75%. 
With 6 core CPU, the load is 17% per miner.
I am working on windows 10, can't tell about macos or linux but surely same as miner app not MP.

**Comment by aspect** [comment]
ah. I completely forgot that this miner is single-core.   regardless, due to the fact that this is not a real-world scenario (i.e. feature needed outside of a testing realm), we won't implement this right now.
