### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by ghost** [aspectron/kdx#43]
Q: "[KDX translation - I can't find this and some error messages.](https://discord.com/channels/599153230659846165/1094031353516925078/1102223312110759968)"
A: I think that developers of KDX should check all strings on all app screens with missing translations by themselves. If we open 100 reports for missing translation that will be a mess"

**Comment by Csubi76** [comment]
> Q: "[KDX translation - I can't find this and some error messages.](https://discord.com/channels/599153230659846165/1094031353516925078/1102223312110759968)" A: I think that developers of KDX should check all strings on all app screens with missing translations by themselves. If we open 100 reports for missing translation that will be a mess"

Good idea. Not excluding error messages.

**Comment by supertypo** [comment]
Translation package has been updated
