### ISSUE TITLE
How to run Linux version?

### ISSUE THREAD

**Issue by Openwrtfunboy** [aspectron/kdx#50]
Double click to KDX does nothing even if i press launch in Konsole, kubuntu 22.04.

**Comment by supertypo** [comment]
Install prerequisites using the terminal:
sudo apt install libnss3 libasound2 libstdc++6

If it still doesnt work: 
cd /path/to/kdx/folder (replace with the actual kdx unzip location)
./kdx

Append the output from that command as a comment in this issue.

**Comment by Openwrtfunboy** [comment]
./kdx

Well, that was the issue. Right click to kdx and Run in Konsole won't work, but manually typing in Konsole ./kdx make it work.

Thanks. But anyway would be cool if there will be AppImage and Flatpack/Snap, with them all simple as on Windows. Just double click and it works.
