### ISSUE TITLE
API error (100): Rejected transaction

### ISSUE THREAD

**Issue by rahmsis** [aspectron/kdx#63]
Can someone please help, i cant send from wallet, all my funds are stuck, this happened after i tried to send some kaspa to the krc wallet kasware

API error (100): Rejected transaction 7d02c783f6f474a2cbd4ef9bfbb6015daa626e138494c9d51a30acc10cad15f0: output (a8768548e965a5a7a52a0488534cf18cf6b508d3096476c5e868e687388b0012, 1) already spent by transaction 2edc3a7e7e5f817271d48a4515edeebbee40400a0d5ee3d9e3b5f68bf51f637d in the memory pool
{"mass":1151,"satoshis":4688904664601,"utxoCount":1,"utxos":[{"address":"kaspa:qqpjfs5gp543njms2xhj2277zm2hl4rclr3wv6zca3aanh942z6ucemqyygt3","txId":"a8768548e965a5a7a52a0488534cf18cf6b508d3096476c5e868e687388b0012","outputIndex":1,"script":"32 0x0324c2880d2b19cb7051af252bde16d57fd478f8e2e66858ec7bd9dcb550b5cc OP_CHECKSIG","satoshis":4688904664601,"blockDaaScore":"76971568","scriptPublicKeyVersion":0,"id":"a8768548e965a5a7a52a0488534cf18cf6b508d3096476c5e868e687388b00121","signatureOPCount":1,"mass":1151,"isCoinbase":false,"scriptPubKey":"200324c2880d2b19cb7051af252bde16d57fd478f8e2e66858ec7bd9dcb550b5ccac"}]}

{"transaction":{"version":0,"inputs":[{"previousOutpoint":{"transactionId":"a8768548e965a5a7a52a0488534cf18cf6b508d3096476c5e868e687388b0012","index":1},"signatureScript":"41df3d302a094391fd43144d85070a6c5cbafbe7327027d3c3cc733cea5944ad4305267a1a4701ef5e9fe4db43e102c55629c983d8b5080182d725bb21c5f934ef01","sequence":0,"sigOpCount":1}],"outputs":[{"amount":9900000000,"scriptPublicKey":{"scriptPublicKey":"20a5349c732978bba9e161b113a3b2643310e8ec2d8ec3d7175bab6b40e0a9ed17ac","version":0}},{"amount":4678904664601,"scriptPublicKey":{"scriptPublicKey":"20ef1a8cc43d95c8a11c4d665dedb04660dec35b559c1ba6c6e4280a01289f8c6fac","version":0}}],"lockTime":0,"payloadHash":"0000000000000000000000000000000000000000000000000000000000000000","subnetworkId":"0000000000000000000000000000000000000000","fee":100000000}}

**Comment by demisrael** [comment]
Kaspa network was under stress, mempool queue was 30k due to KRC-20 tokens minting. The only way to get in the head of queue was high fee. When you sent transaction with default fee, it was stuck on tail of queue and was released recently, after about 5 hours. Next time you can set higher fee, for example - I sent 1k of kaspa with fee of 1kas and it was immediately arrived at kasware wallet.

**Comment by rahmsis** [comment]
Thank for your response
