### ISSUE TITLE
Receive address changed in KDX

### ISSUE THREAD

**Issue by MathijsNL** [aspectron/kdx#64]
**Describe the bug**
My balance is showing up correctly, but the receive address changed somehow.

**To Reproduce**
Not sure, I only noticed the change

**Expected behavior**
The receive address should not change.

**Screenshots**
Here is a screenshot of the wallet as it is showing up right now
![image](https://github.com/user-attachments/assets/f4752c4c-14f2-45a3-8916-a41d50d107a2)

But the balance is actually from another address
![image](https://github.com/user-attachments/assets/168aee3c-ca69-46cf-91c6-e25e3dec9977)

Not sure what happened here, I haven't updated the application. I did delete the full kaspad folder at one point but that should not matter I guess.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22]
 - Wallet version: [e.g. 2.12.10]

**Additional info**
I just recreated the wallet using the 12 words, and this gives me the same result. It shows the right balance for my old receive address but it still shows the wrong receive address.

**Comment by supertypo** [comment]
The displayed receive address will change automatically as soon as it has been used to receive funds, all previous addresses are still valid.

**Comment by MathijsNL** [comment]
Ahh that makes sense. Putting this here for reference:
https://wiki.kaspa.org/en/faq#why-is-it-there-so-many-addresses-in-the-rich-list-but-only-12k-followers-on-twitter
