### ISSUE TITLE
In the Japanese and Chinese interface, clicking the exit button does not respond.

### ISSUE THREAD

**Issue by amaoback** [aspectron/kdx#9]
In the Japanese and Chinese interface, clicking the exit button does not respond.
![image](https://user-images.githubusercontent.com/102347309/160067788-f82c215e-2c84-4df3-82fe-c761245efc84.png)
![image](https://user-images.githubusercontent.com/102347309/160067821-df0ba7ae-c605-41b4-9bf4-2b774671bea1.png)

**Comment by surinder83singh** [comment]
issue resolved
